Add launch file for QR code reader
clubcapra/markhor pull request #13
Opened 2021-06-05 21:05 UTC by CloeD

Launch file to start nodes for viewing QR codes and retrieving data from them. 
Library used: http://wiki.ros.org/visp_auto_tracker

2021-06-12 21:26 UTC, IceSentry reviewed
Il manquerait juste un exec_depend dans package.xml

2021-06-12 21:36 UTC, lvanasse commented
Il manque aussi la dépendance dans le package.xml. Cela va permettre à rosdep d'installer la dépendance lorsqu'on va avoir un nouveau système.

2021-06-12 21:40 UTC, lvanasse requested changes
Maybe add these little edits inside the package.xml and it should be good

2021-06-12 21:45 UTC, CloeD commented
Dépendence ajoutée

2021-06-12 21:46 UTC, lvanasse commented on markhor_bringup/package.xml
I think we will need the  `build_depend`  tag also. See this page http://wiki.ros.org/ROS/Tutorials/rosdep

2021-06-26 16:51 UTC, lvanasse approved these changes
Yes parfait!

2021-06-26 19:22 UTC, merged