Navigation
clubcapra/markhor pull request #58
Opened 2023-06-10 14:58 UTC by SimonR99

Add navigation, 2D slam, 3D slam (RTABMAP), frontier exploration, IMU/velodyne support

2023-06-10 18:52 UTC, Leuchak requested changes
Good work

2023-06-10 18:52 UTC, Leuchak commented on markhor_slam/launch/markhor_slam_2d.launch
> +
trailing whitespace

2023-06-10 19:45 UTC, Leuchak requested changes

2023-06-10 19:45 UTC, Leuchak commented on markhor_navigation/scripts/explore_and_return.py
> +    try:
oops, I meant 2 \n

2023-06-10 20:07 UTC, Leuchak approved these changes
look good

2023-06-11 10:37 UTC, saxtot reviewed
Some things to change. Great work overall.

2023-06-11 10:37 UTC, saxtot commented on markhor_gazebo/launch/local.launch
Old file, to be removed.

2023-06-11 10:37 UTC, saxtot commented on markhor_navigation/CMakeLists.txt
> +    # DEPENDS system_lib
Unnecessary comments. Same thing on lines 34 and 35.

2023-06-11 10:37 UTC, saxtot commented on markhor_navigation/launch/markhor_configuration.launch
Empty file, to be removed.

2023-06-11 10:37 UTC, saxtot commented on markhor_navigation/scripts/explore_and_return.py
> +        rospy.spin()
Might want to consider a ROS [rate](https://roboticsbackend.com/ros-rate-roscpy-roscpp/).

2023-06-11 10:37 UTC, saxtot commented on markhor_slam/launch/markhor_slam_2d.launch
> +        <param name="use_inf" value="false" />
Would be cool to have the units of measurement associated as comments.

2023-06-11 10:37 UTC, saxtot commented on markhor_slam/launch/markhor_slam_2d.launch
> +    Run rtabmap -->
yuck

2023-06-11 14:50 UTC, merged