:sparkles: Add wifi signaltopic to slam files
clubcapra/markhor pull request #66
Opened 2023-06-12 15:32 UTC by saxtot

2023-06-12 20:40 UTC, SimonR99 commented
Good job !

2023-06-12 20:40 UTC, SimonR99 approved these changes

2023-06-13 06:45 UTC, SimonR99 requested changes
We should have the signal launch file in the slam or navigation launch file since this is related to at least one of those two. (At least for now).

2023-06-13 07:51 UTC, saxtot commented
> We should have the signal launch file in the slam or navigation launch file since this is related to at least one of those two. (At least for now).

As discussed, we'll add them when the relation has been setup.

2023-06-13 07:53 UTC, merged